### ISSUE TITLE
pio train error

### ISSUE THREAD

**Issue by itrack** [PredictionIO/PredictionIO#142]
root@predictionio:~/PredictionIO/projects/gamestock# pio build
[INFO] [Console$] Using command '/root/PredictionIO/sbt/sbt' at the current working directory to build.
[INFO] [Console$] If the path above is incorrect, this process will fail.
[INFO] [Console$] Uber JAR disabled. Making sure lib/pio-assembly-0.9.4.jar is absent.
[INFO] [Console$] Going to run: /root/PredictionIO/sbt/sbt  package assemblyPackageDependency
[INFO] [Console$] Build finished successfully.
[INFO] [Console$] Looking for an engine...
[INFO] [Console$] Found barebone-template-assembly-0.1-SNAPSHOT-deps.jar
[INFO] [Console$] Found barebone-template_2.10-0.1-SNAPSHOT.jar
[INFO] [RegisterEngine$] Registering engine Hl61haQisNbI5o647wgC6vVUYfGrNzFZ 5c50cde6f1133230fce2db8993cb70f4636f9d42
[INFO] [Console$] Your engine is ready for training.

------------------------

root@predictionio:~/PredictionIO/projects/gamestock# pio train
[INFO] [Console$] Using existing engine manifest JSON at /root/PredictionIO/projects/gamestock/manifest.json
[INFO] [Runner$] Submission command: /root/PredictionIO/vendors/spark-1.4.1/bin/spark-submit --class io.prediction.workflow.CreateWorkflow --jars file:/root/PredictionIO/projects/gamestock/target/scala-2.10/barebone-template-assembly-0.1-SNAPSHOT-deps.jar,file:/root/PredictionIO/projects/gamestock/target/scala-2.10/barebone-template_2.10-0.1-SNAPSHOT.jar --files file:/root/PredictionIO/conf/log4j.properties,file:/root/PredictionIO/vendors/hbase-1.0.0/conf/hbase-site.xml --driver-class-path /root/PredictionIO/conf:/root/PredictionIO/vendors/hbase-1.0.0/conf file:/root/PredictionIO/lib/pio-assembly-0.9.4.jar --engine-id Hl61haQisNbI5o647wgC6vVUYfGrNzFZ --engine-version 5c50cde6f1133230fce2db8993cb70f4636f9d42 --engine-variant file:/root/PredictionIO/projects/gamestock/engine.json --verbosity 0 --json-extractor Both --env PIO_STORAGE_SOURCES_HBASE_TYPE=hbase,PIO_ENV_LOADED=1,PIO_STORAGE_REPOSITORIES_METADATA_NAME=pio_meta,PIO_FS_BASEDIR=/root/.pio_store,PIO_STORAGE_SOURCES_HBASE_HOME=/root/PredictionIO/vendors/hbase-1.0.0,PIO_HOME=/root/PredictionIO,PIO_FS_ENGINESDIR=/root/.pio_store/engines,PIO_STORAGE_SOURCES_LOCALFS_PATH=/root/.pio_store/models,PIO_STORAGE_SOURCES_ELASTICSEARCH_TYPE=elasticsearch,PIO_STORAGE_REPOSITORIES_METADATA_SOURCE=ELASTICSEARCH,PIO_STORAGE_REPOSITORIES_MODELDATA_SOURCE=LOCALFS,PIO_STORAGE_REPOSITORIES_EVENTDATA_NAME=pio_event,PIO_STORAGE_SOURCES_ELASTICSEARCH_HOME=/root/PredictionIO/vendors/elasticsearch-1.4.4,PIO_FS_TMPDIR=/root/.pio_store/tmp,PIO_STORAGE_REPOSITORIES_MODELDATA_NAME=pio_model,PIO_STORAGE_REPOSITORIES_EVENTDATA_SOURCE=HBASE,PIO_CONF_DIR=/root/PredictionIO/conf,PIO_STORAGE_SOURCES_LOCALFS_TYPE=localfs
Exception in thread "main" scala.reflect.internal.MissingRequirementError: object com.gamestock.RecommendationEngine not found.
	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
	at scala.reflect.internal.Mirrors$RootsBase.ensureModuleSymbol(Mirrors.scala:126)
	at scala.reflect.internal.Mirrors$RootsBase.staticModule(Mirrors.scala:161)
	at scala.reflect.internal.Mirrors$RootsBase.staticModule(Mirrors.scala:21)
	at io.prediction.workflow.WorkflowUtils$.getEngine(WorkflowUtils.scala:64)
	at io.prediction.workflow.CreateWorkflow$.liftedTree1$1(CreateWorkflow.scala:193)
	at io.prediction.workflow.CreateWorkflow$.main(CreateWorkflow.scala:192)
	at io.prediction.workflow.CreateWorkflow.main(CreateWorkflow.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:665)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:170)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:193)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:112)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by pferrel** [comment]
Look in your scala files and see what the package name is. The error for a missing com.gamestock.RecommendationEngine usually means the code uses the org.template package prefix, which means you may not have used the download script but got the template directly from github.
