### ISSUE TITLE
org.apache.hadoop.net.DNS.reverseDns(DNS.java:92)

### ISSUE THREAD

**Issue by wayne-o** [PredictionIO/PredictionIO#207]
Had this error after installing on OSX so uninstalled and downloaded the vagrant box and got the same. Any ideas?

```
[INFO] [Engine] Extracting datasource params...
[INFO] [WorkflowUtils$] No 'name' is found. Default empty String will be used.
[INFO] [Engine] Datasource params: (,DataSourceParams(SonatribeRecommendations,List(purchase, view)))
[INFO] [Engine] Extracting preparator params...
[INFO] [Engine] Preparator params: (,Empty)
[INFO] [Engine] Extracting serving params...
[INFO] [Engine] Serving params: (,Empty)
[INFO] [Remoting] Starting remoting
[INFO] [Remoting] Remoting started; listening on addresses :[akka.tcp://sparkDriver@10.0.2.15:47059]
[WARN] [MetricsSystem] Using default name DAGScheduler for source because spark.app.id is not set.
[INFO] [Engine$] EngineWorkflow.train
[INFO] [Engine$] DataSource: com.sonatribe.DataSource@348c8206
[INFO] [Engine$] Preparator: com.sonatribe.Preparator@74243d88
[INFO] [Engine$] AlgorithmList: List(com.sonatribe.URAlgorithm@35407ec)
[INFO] [Engine$] Data sanity check is on.
Exception in thread "main" java.lang.NullPointerException
	at org.apache.hadoop.net.DNS.reverseDns(DNS.java:92)
	at org.apache.hadoop.hbase.mapreduce.TableInputFormatBase.reverseDNS(TableInputFormatBase.java:228)
	at org.apache.hadoop.hbase.mapreduce.TableInputFormatBase.getSplits(TableInputFormatBase.java:191)
	at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:115)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.Partitioner$.defaultPartitioner(Partitioner.scala:65)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$aggregateByKey$3.apply(PairRDDFunctions.scala:164)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$aggregateByKey$3.apply(PairRDDFunctions.scala:164)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
	at org.apache.spark.rdd.PairRDDFunctions.aggregateByKey(PairRDDFunctions.scala:163)
	at io.prediction.data.storage.PEventAggregator$.aggregateProperties(PEventAggregator.scala:198)
	at io.prediction.data.storage.PEvents$class.aggregateProperties(PEvents.scala:118)
	at io.prediction.data.storage.hbase.HBPEvents.aggregateProperties(HBPEvents.scala:33)
	at io.prediction.data.store.PEventStore$.aggregateProperties(PEventStore.scala:112)
	at com.sonatribe.DataSource.readTraining(DataSource.scala:83)
	at com.sonatribe.DataSource.readTraining(DataSource.scala:46)
	at io.prediction.controller.PDataSource.readTrainingBase(PDataSource.scala:37)
	at io.prediction.controller.Engine$.train(Engine.scala:640)
	at io.prediction.controller.Engine.train(Engine.scala:174)
	at io.prediction.workflow.CoreWorkflow$.runTrain(CoreWorkflow.scala:65)
	at io.prediction.workflow.CreateWorkflow$.main(CreateWorkflow.scala:247)
	at io.prediction.workflow.CreateWorkflow.main(CreateWorkflow.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by wayne-o** [comment]
This is after calling ```pio train``` BTW

**Comment by djones** [comment]
https://docs.prediction.io/resources/faq/#running-hbase
