### ISSUE TITLE
pio train error

### ISSUE THREAD

**Issue by phiripatrick663** [PredictionIO/PredictionIO#232]
I want to use the classification template and found this example of template modification to be the best fit for how I would like to customize my project. I decide to run this example to better understand how it works, so have all files looking exactly like the ones here. 

I ran into some evaluation errors before realizing that I needed to remove the evaluation scripts. So, now my build is going fine but am getting an error during training:

Exception in thread "main" java.lang.NoClassDefFoundError: io/prediction/controller/IEngineFactory$class
	at com.test1.ClassificationEngine$.<init>(Engine.scala:16)
	at com.test1.ClassificationEngine$.<clinit>(Engine.scala)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at scala.reflect.runtime.ReflectionUtils$.staticSingletonInstance(ReflectionUtils.scala:60)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaModuleMirror.instance(JavaMirrors.scala:473)
	at io.prediction.workflow.WorkflowUtils$.getEngine(WorkflowUtils.scala:69)
	at io.prediction.workflow.CreateWorkflow$.liftedTree1$1(CreateWorkflow.scala:193)
	at io.prediction.workflow.CreateWorkflow$.main(CreateWorkflow.scala:192)
	at io.prediction.workflow.CreateWorkflow.main(CreateWorkflow.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: io.prediction.controller.IEngineFactory$class
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 19 more
I have done some searches in the forums and did not find anything to help fix this error. What could be causing this error?

I would like to see this example run because it gives me the best route to my own customization. 

Please help!
Thanks.

**Comment by phiripatrick663** [comment]
Could someone point me in the right direction please. Why am I getting this error? I really have not come across any indication of what might be going wrong.

Thanks in advance.

**Comment by alex9311** [comment]
you removed the Evaluation.scala file?

**Comment by phiripatrick663** [comment]
I was getting a build error with the evaluation files in folder to start,
so I just took them out and build was successful.
