### ISSUE TITLE
The hdfs-site.xml should be included in the --files passed to Spark Submit

### ISSUE THREAD

**Issue by younes-abouelnagah** [PredictionIO/PredictionIO#236]
Pio has been lucky that [HADOOP_CONF_DIR is actually recognized by Spark](https://github.com/apache/spark/blob/v1.6.1/docs/configuration.md#inheriting-hadoop-cluster-configuration), because that's the reason why the Hadoop configurations are correctly loaded. PIO [currently takes only core-site.xml from HADOOP_CONF_DIR](https://github.com/PredictionIO/PredictionIO/blob/362b77da4e5787fc73c2fb8492eb54676f8cff8f/core/src/main/scala/io/prediction/workflow/WorkflowUtils.scala#L245), which results in a NoClassDefFoundError upon initializing the DFSClient. The exception below is the real error, since core-site.xml does not usually contain the mapping from nameservice to actual hosts. This mapping should be in the hdfs-site.xml, even though nothing prevents anybody from putting it in core-site.xml. Without getting into much details about the different ways to configure Hadoop, please include hdfs-site.xml in the --files passed to spark submit. 

> Caused by: java.lang.IllegalArgumentException: java.net.UnknownHostException: nameservice1
> at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:374)
> at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:312)
> at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:178)
> at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:665)
> at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:601)
> at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:148)
> at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2596)
> at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:91)
> at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2630)
> at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2612)
> at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370)
> at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:169)
> at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:354)
> at org.apache.hadoop.fs.Path.getFileSystem(Path.java:296)
> at org.apache.hadoop.hbase.util.DynamicClassLoader.<init>(DynamicClassLoader.java:104)
> at org.apache.hadoop.hbase.protobuf.ProtobufUtil.<clinit>(ProtobufUtil.java:202)

Also, consider using a different environment variable name for HADOOP_CONF_DIR, because the reuse of the same name as the Spark recognized one helped hide this bug for a long time and made tracking it down very difficult. We were seeing this exception sporadically, because it happens only if the task ends up being executed on a machine where the directory HADOOP_CONF_DIR points to doesn't exist. Imagine tracking this down!

**Comment by pferrel** [comment]
Could you repost this on https://github.com/actionml/PredictionIO? It may get fixed faster there.

**Comment by younes-abouelnagah** [comment]
Done.. thanks Pat.
