### ISSUE TITLE
pio train fails because of (java.io.IOException: Cannot run program "/home/tigra/PredictionIO/vendors/spark-1.6.0/bin/spark-submit": error=2, No such file or directory)

### ISSUE THREAD

**Issue by tigra** [PredictionIO/PredictionIO#241]
Installed PredictionIO, chose template Universal Recommender, built it, put got error trying to train the model (spark-submit file not found - and it is really not present):

OS: Ubuntu 14.04.4 LTS

Installed PredictionIO with:
$ bash -c "$(curl -s https://install.prediction.io/install.sh)"

Installed to /home/tigra/PredictionIO (ran install script under user tigra).

Chose to install with Elasticsearch & HBase

$ pio-start-all 
Starting Elasticsearch...
Starting HBase...
starting master, logging to /home/tigra/PredictionIO/vendors/hbase-1.1.2/bin/../logs/hbase-tigra-master-iseland.out
Waiting 10 seconds for HBase to fully initialize...
Starting PredictionIO Event Server...

$ pio template get PredictionIO/template-scala-parallel-universal-recommendation AmpleUni2
/home/tigra/PredictionIO/vendors/spark-1.6.0 is probably an Apache Spark development tree. Please make sure you are using at least 1.3.0.
Please enter the template's Scala package name (e.g. com.mycompany): com.tigra.test
Author's name:         tigra
Author's e-mail:       tigra@nlp.od.ua
Author's organization: com.tigra.test
Would you like to be informed about new bug fixes and security updates of this template? (Y/n) y
Retrieving PredictionIO/template-scala-parallel-universal-recommendation
There are 6 tags
Using tag v0.2.3
Going to download https://github.com/PredictionIO/template-scala-parallel-universal-recommendation/archive/v0.2.3.zip
Redirecting to https://codeload.github.com/PredictionIO/template-scala-parallel-universal-recommendation/zip/v0.2.3
Replacing org.template with com.tigra.test...
Processing AmpleUni2/build.sbt...
Processing AmpleUni2/engine.json...
Processing AmpleUni2/src/main/scala/DataSource.scala...
Processing AmpleUni2/src/main/scala/Engine.scala...
Processing AmpleUni2/src/main/scala/PopModel.scala...
Processing AmpleUni2/src/main/scala/Preparator.scala...
Processing AmpleUni2/src/main/scala/Serving.scala...
Processing AmpleUni2/src/main/scala/URAlgorithm.scala...
Processing AmpleUni2/src/main/scala/URModel.scala...
Processing AmpleUni2/src/main/scala/esClient.scala...
Processing AmpleUni2/src/main/scala/package.scala...
Engine template PredictionIO/template-scala-parallel-universal-recommendation is now ready at AmpleUni2

$ cd AmpleUni2/
$ pio build
/home/tigra/PredictionIO/vendors/spark-1.6.0 is probably an Apache Spark development tree. Please make sure you are using at least 1.3.0.
[INFO] [Console$] Using command '/home/tigra/PredictionIO/sbt/sbt' at the current working directory to build.
[INFO] [Console$] If the path above is incorrect, this process will fail.
[INFO] [Console$] Uber JAR disabled. Making sure lib/pio-assembly-0.9.6.jar is absent.
[INFO] [Console$] Going to run: /home/tigra/PredictionIO/sbt/sbt  package assemblyPackageDependency
															[INFO] [Console$] Build finished successfully.
										[INFO] [Console$] Looking for an engine...
															[INFO] [Console$] Found template-scala-parallel-universal-recommendation_2.10-0.2.3.jar
[INFO] [Console$] Found template-scala-parallel-universal-recommendation-assembly-0.2.3-deps.jar
															[INFO] [RegisterEngine$] Registering engine 2IaCYMBTdvRE46qNz96heDxxAdxgl771 06cf351d8b41133a8da56ab68fa9220af58eb85c
															[INFO] [Console$] Your engine is ready for training.
						
$ pio train
/home/tigra/PredictionIO/vendors/spark-1.6.0 is probably an Apache Spark development tree. Please make sure you are using at least 1.3.0.
[INFO] [Console$] Using existing engine manifest JSON at /home/tigra/AmpleUni2/manifest.json
[INFO] [Runner$] Submission command: /home/tigra/PredictionIO/vendors/spark-1.6.0/bin/spark-submit --class io.prediction.workflow.CreateWorkflow --jars file:/home/tigra/AmpleUni2/target/scala-2.10/template-scala-parallel-universal-recommendation_2.10-0.2.3.jar,file:/home/tigra/AmpleUni2/target/scala-2.10/template-scala-parallel-universal-recommendation-assembly-0.2.3-deps.jar --files file:/home/tigra/PredictionIO/conf/log4j.properties,file:/home/tigra/PredictionIO/vendors/hbase-1.1.2/conf/hbase-site.xml --driver-class-path /home/tigra/PredictionIO/conf:/home/tigra/PredictionIO/lib/postgresql-9.4-1204.jdbc41.jar:/home/tigra/PredictionIO/lib/mysql-connector-java-5.1.37.jar:/home/tigra/PredictionIO/vendors/hbase-1.1.2/conf file:/home/tigra/PredictionIO/lib/pio-assembly-0.9.6.jar --engine-id 2IaCYMBTdvRE46qNz96heDxxAdxgl771 --engine-version 06cf351d8b41133a8da56ab68fa9220af58eb85c --engine-variant file:/home/tigra/AmpleUni2/engine.json --verbosity 0 --json-extractor Both --env PIO_STORAGE_SOURCES_HBASE_TYPE=hbase,PIO_ENV_LOADED=1,PIO_STORAGE_REPOSITORIES_METADATA_NAME=pio_meta,PIO_FS_BASEDIR=/home/tigra/.pio_store,PIO_STORAGE_SOURCES_HBASE_HOME=/home/tigra/PredictionIO/vendors/hbase-1.1.2,PIO_HOME=/home/tigra/PredictionIO,PIO_FS_ENGINESDIR=/home/tigra/.pio_store/engines,PIO_STORAGE_SOURCES_LOCALFS_PATH=/home/tigra/.pio_store/models,PIO_STORAGE_SOURCES_ELASTICSEARCH_TYPE=elasticsearch,PIO_STORAGE_REPOSITORIES_METADATA_SOURCE=ELASTICSEARCH,PIO_STORAGE_REPOSITORIES_MODELDATA_SOURCE=LOCALFS,PIO_STORAGE_REPOSITORIES_EVENTDATA_NAME=pio_event,PIO_STORAGE_SOURCES_ELASTICSEARCH_HOME=/home/tigra/PredictionIO/vendors/elasticsearch-1.7.3,PIO_FS_TMPDIR=/home/tigra/.pio_store/tmp,PIO_STORAGE_REPOSITORIES_MODELDATA_NAME=pio_model,PIO_STORAGE_REPOSITORIES_EVENTDATA_SOURCE=HBASE,PIO_CONF_DIR=/home/tigra/PredictionIO/conf,PIO_STORAGE_SOURCES_LOCALFS_TYPE=localfs
Exception in thread "main" java.io.IOException: Cannot run program "/home/tigra/PredictionIO/vendors/spark-1.6.0/bin/spark-submit": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:68)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:97)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:96)
	at io.prediction.tools.Runner$.runOnSpark(Runner.scala:201)
	at io.prediction.tools.RunWorkflow$.newRunWorkflow(RunWorkflow.scala:206)
	at io.prediction.tools.console.Console$$anonfun$train$1.apply(Console.scala:840)
	at io.prediction.tools.console.Console$$anonfun$train$1.apply(Console.scala:839)
	at scala.Option.map(Option.scala:145)
	at io.prediction.tools.console.Console$.withRegisteredManifest(Console.scala:1214)
	at io.prediction.tools.console.Console$.train(Console.scala:839)
	at io.prediction.tools.console.Console$$anonfun$main$1.apply(Console.scala:713)
	at io.prediction.tools.console.Console$$anonfun$main$1.apply(Console.scala:693)
	at scala.Option.map(Option.scala:145)
	at io.prediction.tools.console.Console$.main(Console.scala:693)
	at io.prediction.tools.console.Console.main(Console.scala)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 15 more

**Comment by vangorra** [comment]
I am also having the same issue running on Ubuntu 16.04. I noticed the following output during the install: 

```
Starting Spark setup in: /home/myuser/.local/share/PredictionIO/vendors/spark-1.6.0

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
Updating: /home/myuser/.local/share/PredictionIO/conf/pio-env.sh
Spark setup done!
```

**Comment by vangorra** [comment]
After some troubleshooting, I realized the spark tgz file wasn't properly downloaded. So I removed /tmp/spark-1.6.0-bin-hadoop2.6.tgz and reran the install. The error is not longer occurring.

**Comment by pferrel** [comment]
Sorry folks but the UR requires the ActionML fork of PIO. The PIO repository we are commenting on has not been maintained and is being moved to Apache.

In the meantime I suggest you follow the docs on actionml.com/docs. You'll need to get PredictionIO-0.9.7-aml here: actionml.com/docs/install.sh and the Universal Recommender here: actionml.com/docs/ur

Also you'll get answers quicker if you move questions to: https://groups.google.com/forum/#!forum/actionml-user

**Comment by Christophy** [comment]
@pferrel Thanks for the reply, but it seems the docs on actionml.com/docs cant be accessed currently.

**Comment by pferrel** [comment]
The monitor says it running and I can access, what do you see? Are you using Chrome?

**Comment by Christophy** [comment]
@pferrel 
yes,im using chrome, just see the screen shot below:
![ddd](https://cloud.githubusercontent.com/assets/4383579/16325034/ef5fdaea-39ec-11e6-91a5-6487cf59ead3.png)
and this is what I found on google
http://stackoverflow.com/questions/36031706/middleware-stack-js31-uncaught-error-handler-with-name-route-already-exists

**Comment by pferrel** [comment]
Yes, I have updated the server last week to fix this but will research more. Thanks!

**Comment by pferrel** [comment]
I rebooted after the iron-router upgrade to do a clean start and meteor reverted the change--grrr--so the SO answer was very helpful. I've done a permanent upgrade and checked the running version which seems to include the fix. Can you try again?

And thanks again!

**Comment by Christophy** [comment]
@pferrel I can access the docs now , thanks a lot!
btw, I'd love to contribute to the project but I can hardly understand the code written in scala, any suggestions for a quick start? I am a javascript developer.
