### ISSUE TITLE
Vagrant event server fails to start

### ISSUE THREAD

**Issue by HintikkaKimmo** [PredictionIO/PredictionIO#37]
Hi, I tried the Vagrant install on this project with following outcome.

Installation script completes with no errors, but when I try to start event server I get following error. Error is really long but I think the base point is Zookeeper is not starting up. I tried to find Zookeeper config files to start it manually but I am not able to locate them. Could something be missing on the image?

^Cvagrant@vagrant-ubuntu-trusty-64:~$ pio eventserver
2015-01-19 18:00:33,812 INFO  tools.Console$ - Creating Event Server at localhost:7070
2015-01-19 18:00:37,390 ERROR zookeeper.RecoverableZooKeeper - ZooKeeper exists failed after 1 attempts
2015-01-19 18:00:37,391 ERROR zookeeper.ZooKeeperWatcher - hconnection-0x779122a0, quorum=localhost:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/hbaseid
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1045)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:199)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:479)
	at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:65)
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:83)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.retrieveClusterId(HConnectionManager.java:852)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.<init>(HConnectionManager.java:657)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:409)
	at org.apache.hadoop.hbase.client.HConnectionManager.createConnection(HConnectionManager.java:388)
	at org.apache.hadoop.hbase.client.HConnectionManager.getConnection(HConnectionManager.java:269)
	at org.apache.hadoop.hbase.client.HBaseAdmin.checkHBaseAvailable(HBaseAdmin.java:2338)
	at io.prediction.data.storage.hbase.StorageClient.<init>(StorageClient.scala:48)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at io.prediction.data.storage.Storage$.getClient(Storage.scala:155)
	at io.prediction.data.storage.Storage$.io$prediction$data$storage$Storage$$updateS2CM(Storage.scala:70)
	at io.prediction.data.storage.Storage$$anonfun$sourcesToClientMetaGet$1.apply(Storage.scala:84)
	at io.prediction.data.storage.Storage$$anonfun$sourcesToClientMetaGet$1.apply(Storage.scala:84)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
	at io.prediction.data.storage.Storage$.sourcesToClientMetaGet(Storage.scala:84)
	at io.prediction.data.storage.Storage$.sourcesToClientMeta(Storage.scala:90)
	at io.prediction.data.storage.Storage$.getDataObject(Storage.scala:193)
	at io.prediction.data.storage.Storage$.getDataObject(Storage.scala:178)
	at io.prediction.data.storage.Storage$.getLEvents(Storage.scala:274)
	at io.prediction.data.api.EventServer$.createEventServer(EventAPI.scala:297)
	at io.prediction.tools.Console$.eventserver(Console.scala:937)
	at io.prediction.tools.Console$$anonfun$main$1.apply(Console.scala:669)
	at io.prediction.tools.Console$$anonfun$main$1.apply(Console.scala:631)
	at scala.Option.map(Option.scala:145)
	at io.prediction.tools.Console$.main(Console.scala:631)
	at io.prediction.tools.Console.main(Console.scala)
2015-01-19 18:00:39,595 ERROR storage.Storage$ - Error initializing storage client for source HBASE
2015-01-19 18:00:39,597 ERROR storage.Storage$ - Can't connect to ZooKeeper
Exception in thread "main" java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:313)
	at scala.None$.get(Option.scala:311)
	at io.prediction.data.storage.Storage$.sourcesToClientMeta(Storage.scala:90)
	at io.prediction.data.storage.Storage$.getDataObject(Storage.scala:193)
	at io.prediction.data.storage.Storage$.getDataObject(Storage.scala:178)
	at io.prediction.data.storage.Storage$.getLEvents(Storage.scala:274)
	at io.prediction.data.api.EventServer$.createEventServer(EventAPI.scala:297)
	at io.prediction.tools.Console$.eventserver(Console.scala:937)
	at io.prediction.tools.Console$$anonfun$main$1.apply(Console.scala:669)
	at io.prediction.tools.Console$$anonfun$main$1.apply(Console.scala:631)
	at scala.Option.map(Option.scala:145)
	at io.prediction.tools.Console$.main(Console.scala:631)
	at io.prediction.tools.Console.main(Console.scala)

**Comment by HintikkaKimmo** [comment]
Anyway I plan to make manual install on a local VM tonight to see if that gets me running.

**Comment by dszeto** [comment]
Hi @HintikkaKimmo , would you mind posting HBase logs in $HOME/PredictionIO/vendors/hbase-0.98.6/logs please? The default installation runs HBase in standalone mode, which has an embedded ZooKeeper.

**Comment by HintikkaKimmo** [comment]
I think this is not a Predict IO issue but something in my vagrant & VBox installation. I cannot even vagrant up the machine again. I get error below. Box status shows it is not running but vagrant up gives >

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["sharedfolder", "add", "89315de5-b135-462f-8e3a-8403d1b0068b", "--name", "vagrant", "--hostpath", "/Users/kimmo/PredictionIO-Vagrant"]

Stderr: VBoxManage: error: The machine 'PredictionIO-Vagrant_default_1421614504019_46707' is already locked for a session (or being unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component Machine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 1002 of file VBoxManageMisc.cpp

I am going to destroy it and try again to see if error repeats or is there a way to get the logs without ssh to to the machine as there is no local shared folder. If it happens again I reopen.
